# Generated by Django 6.0 on 2026-02-05 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=12, unique=True)),
                ('cik', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('exchange', models.CharField(blank=True, default='', max_length=32)),
                ('sector', models.CharField(blank=True, default='', max_length=128)),
                ('industry', models.CharField(blank=True, default='', max_length=128)),
                ('sic_code', models.CharField(blank=True, default='', max_length=8)),
                ('sic_description', models.CharField(blank=True, default='', max_length=255)),
                ('market_cap_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='FaithScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment_score', models.PositiveSmallIntegerField(default=0)),
                ('base_score', models.PositiveSmallIntegerField(default=0)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('pipeline_version', models.CharField(default='v0.1', max_length=32)),
                ('llm_provider', models.CharField(blank=True, default='', max_length=32)),
                ('llm_model', models.CharField(blank=True, default='', max_length=64)),
                ('base_findings', models.JSONField(blank=True, default=dict)),
                ('category_details', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('raw_classification', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faith_screen', to='faith_alpha.company')),
            ],
            options={
                'ordering': ['-alignment_score', 'company__ticker'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('10-K', '10-K'), ('DEF 14A', 'DEF 14A'), ('OTHER', 'OTHER')], default='OTHER', max_length=16)),
                ('accession_number', models.CharField(max_length=32)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('primary_document', models.CharField(blank=True, default='', max_length=255)),
                ('source_url', models.URLField(max_length=600)),
                ('content_text', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='faith_alpha.company')),
            ],
            options={
                'ordering': ['company_id', '-filing_date'],
                'indexes': [models.Index(fields=['company', 'form_type', '-filing_date'], name='faith_alpha_company_92fdb5_idx')],
                'unique_together': {('company', 'form_type', 'accession_number')},
            },
        ),
    ]
