# Generated by Django 6.0 on 2026-02-05 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith_alpha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('fec', 'FEC'), ('lda', 'Senate LDA'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('signal_type', models.CharField(db_index=True, max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cycle_or_year', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_text', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('retrieved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='faith_alpha.company')),
            ],
            options={
                'ordering': ['company_id', 'source', '-cycle_or_year', '-created_at'],
                'indexes': [models.Index(fields=['company', 'source', '-cycle_or_year'], name='faith_alpha_company_211d2a_idx'), models.Index(fields=['company', 'signal_type'], name='faith_alpha_company_7852b6_idx')],
                'unique_together': {('company', 'source', 'signal_type', 'external_id')},
            },
        ),
    ]
