# Generated by Django 5.2.9 on 2025-12-05 23:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodMedian',
            fields=[
                ('neighborhood_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('median_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('property_count', models.IntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_address', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('property_address_normalized', models.CharField(blank=True, max_length=500, null=True)),
                ('cad_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=300, null=True)),
                ('mailing_address', models.CharField(blank=True, max_length=500, null=True)),
                ('mailing_address_normalized', models.CharField(blank=True, max_length=500, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('land_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('improvement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('neighborhood_median', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_absentee', models.BooleanField(db_index=True, default=False)),
                ('homestead_exempt', models.BooleanField(default=False)),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('permits_found', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('log_file', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_id', models.CharField(max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('property_address', models.CharField(max_length=500)),
                ('property_address_normalized', models.CharField(blank=True, max_length=500, null=True)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('permit_type', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_date', models.DateField(blank=True, db_index=True, null=True)),
                ('applicant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead_type', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_subtypes', models.JSONField(blank=True, null=True)),
                ('categorization_confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['property_address_normalized'], name='leads_permi_propert_b2884c_idx')],
                'unique_together': {('city', 'permit_id')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lead_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('lead_subtypes', models.JSONField(blank=True, null=True)),
                ('is_high_contrast', models.BooleanField(default=False)),
                ('contrast_ratio', models.FloatField(blank=True, null=True)),
                ('is_absentee', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, db_index=True, null=True)),
                ('score_breakdown', models.JSONField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, choices=[('A', 'Tier A'), ('B', 'Tier B'), ('C', 'Tier C'), ('D', 'Tier D')], db_index=True, max_length=1, null=True)),
                ('permit_date', models.DateField(blank=True, null=True)),
                ('days_since_permit', models.IntegerField(blank=True, null=True)),
                ('freshness_tier', models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('moderate', 'Moderate'), ('cool', 'Cool'), ('cold', 'Cold'), ('stale', 'Stale')], db_index=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('exported', 'Exported'), ('contacted', 'Contacted'), ('converted', 'Converted')], db_index=True, default='new', max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='clients.Property')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
