# Generated by Django 5.2.9 on 2025-12-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='is_absentee',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='clients.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_absentee',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterModelTable(
            name='lead',
            table='leads_lead',
        ),
        migrations.AlterModelTable(
            name='neighborhoodmedian',
            table='leads_neighborhoodmedian',
        ),
        migrations.AlterModelTable(
            name='permit',
            table='leads_permit',
        ),
        migrations.AlterModelTable(
            name='property',
            table='leads_property',
        ),
        migrations.AlterModelTable(
            name='scraperrun',
            table='leads_scraperrun',
        ),
    ]
