# Generated by Django 5.2.9 on 2025-12-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_allow_null_absentee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_applicant_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_chain_of_thought',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_red_flags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_tier',
            field=models.CharField(blank=True, choices=[('A', 'Tier A'), ('B', 'Tier B'), ('C', 'Tier C'), ('D', 'Tier D')], max_length=1, null=True),
        ),
    ]
