# Generated by Django 5.2.9 on 2025-12-07 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_ai_scoring_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('trade_group', models.CharField(db_index=True, max_length=50)),
                ('is_commercial', models.BooleanField(db_index=True, default=False)),
                ('score', models.IntegerField(db_index=True)),
                ('tier', models.CharField(choices=[('A', 'Tier A - Premium'), ('B', 'Tier B - Good'), ('C', 'Tier C - Low Priority'), ('RETRY', 'Pending Retry')], db_index=True, max_length=5)),
                ('reasoning', models.TextField()),
                ('chain_of_thought', models.TextField(blank=True)),
                ('flags', models.JSONField(default=list)),
                ('ideal_contractor', models.CharField(blank=True, max_length=200)),
                ('contact_priority', models.CharField(choices=[('call', 'Call Today'), ('email', 'Email'), ('skip', 'Skip')], default='email', max_length=20)),
                ('scoring_method', models.CharField(choices=[('ai', 'AI (DeepSeek Chat)'), ('ai-reasoner', 'AI (DeepSeek Reasoner)'), ('pending_retry', 'Pending Retry')], default='ai', max_length=20)),
                ('scored_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'New'), ('exported', 'Exported'), ('sold', 'Sold to Contractor'), ('contacted', 'Homeowner Contacted'), ('converted', 'Converted'), ('dead', 'Dead Lead')], db_index=True, default='new', max_length=20)),
                ('sold_to', models.CharField(blank=True, max_length=200)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cad_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_leads', to='clients.property')),
                ('permit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scored_lead', to='clients.permit')),
            ],
            options={
                'db_table': 'clients_scoredlead',
                'ordering': ['-score', '-scored_at'],
                'indexes': [models.Index(fields=['trade_group', 'category', 'tier'], name='clients_sco_trade_g_fa2eac_idx'), models.Index(fields=['status', 'tier'], name='clients_sco_status_050cf9_idx'), models.Index(fields=['category', 'score'], name='clients_sco_categor_b1f06e_idx')],
            },
        ),
    ]
