# Generated by Django 5.2.9 on 2025-12-02 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('search_terms', models.JSONField(default=list)),
                ('avg_job_value', models.PositiveIntegerField(default=10000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='TX', max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('google_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('google_review_count', models.PositiveIntegerField(default=0)),
                ('google_reviews_json', models.JSONField(blank=True, default=list)),
                ('yelp_id', models.CharField(blank=True, max_length=255, null=True)),
                ('yelp_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('yelp_review_count', models.PositiveIntegerField(default=0)),
                ('bbb_rating', models.CharField(blank=True, max_length=2, null=True)),
                ('bbb_accredited', models.BooleanField(default=False)),
                ('bbb_complaint_count', models.PositiveIntegerField(default=0)),
                ('bbb_years_in_business', models.PositiveIntegerField(blank=True, null=True)),
                ('bbb_url', models.URLField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_status', models.CharField(blank=True, max_length=50, null=True)),
                ('license_type', models.CharField(blank=True, max_length=100, null=True)),
                ('trust_score', models.PositiveIntegerField(default=0)),
                ('passes_threshold', models.BooleanField(default=False)),
                ('verification_score', models.PositiveIntegerField(default=0)),
                ('reputation_score', models.PositiveIntegerField(default=0)),
                ('credibility_score', models.PositiveIntegerField(default=0)),
                ('red_flag_score', models.PositiveIntegerField(default=0)),
                ('bonus_score', models.PositiveIntegerField(default=0)),
                ('admin_score_override', models.PositiveIntegerField(blank=True, null=True)),
                ('admin_override_reason', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_sentiment_score', models.PositiveIntegerField(default=50)),
                ('ai_red_flags', models.JSONField(blank=True, default=list)),
                ('is_claimed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('first_scraped_at', models.DateTimeField(auto_now_add=True)),
                ('last_enriched_at', models.DateTimeField(blank=True, null=True)),
                ('last_audited_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verticals', models.ManyToManyField(blank=True, related_name='contractors', to='contractors.vertical')),
            ],
            options={
                'ordering': ['-trust_score'],
                'unique_together': {('business_name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='ContractorAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateTimeField(auto_now_add=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('sentiment_score', models.PositiveIntegerField(default=50)),
                ('ai_summary', models.TextField(blank=True)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='contractors.contractor')),
            ],
            options={
                'ordering': ['-audit_date'],
            },
        ),
    ]
