# Generated by Django 5.2.9 on 2025-12-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='tier',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('new', 'New Business'), ('unranked', 'Unranked')], default='unranked', max_length=20),
        ),
        migrations.AddField(
            model_name='contractor',
            name='yelp_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
