# Generated by Django 5.2.9 on 2025-12-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_contractor_tier_contractor_yelp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoraudit',
            name='base_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='credibility_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='data_confidence',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='data_gaps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='financial_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='homeowner_guidance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='multiplier_applied',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='multiplier_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='narrative_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='normalized_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='perplexity_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='recommendation',
            field=models.CharField(choices=[('AVOID', 'Avoid'), ('CAUTION', 'Caution'), ('VERIFY', 'Verify'), ('RECOMMENDED', 'Recommended')], default='VERIFY', max_length=20),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='red_flag_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='reputation_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='risk_level',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('SEVERE', 'Severe'), ('MODERATE', 'Moderate'), ('LOW', 'Low'), ('TRUSTED', 'Trusted')], default='MODERATE', max_length=20),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='sources_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='synthesis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractoraudit',
            name='verification_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AuditTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('event', models.TextField()),
                ('significance', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='contractors.contractoraudit')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('SEVERE', 'Severe'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor')], default='MODERATE', max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flags', to='contractors.contractoraudit')),
            ],
            options={
                'ordering': ['severity', 'category'],
            },
        ),
    ]
