# Generated by Django 5.2 on 2025-12-10 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_contractoraudit_base_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('deepseek_tokens_used', models.IntegerField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='contractors.contractor')),
            ],
            options={
                'db_table': 'audit_records',
            },
        ),
        migrations.CreateModel(
            name='CollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.TextField()),
                ('requested_by', models.TextField(blank=True, null=True)),
                ('request_reason', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_logs', to='contractors.contractor')),
            ],
            options={
                'db_table': 'collection_log',
            },
        ),
        migrations.CreateModel(
            name='ContractorRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.TextField()),
                ('source_url', models.TextField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('structured_data', models.JSONField(blank=True, null=True)),
                ('fetch_status', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='contractors.contractor')),
            ],
            options={
                'db_table': 'contractor_raw_data',
            },
        ),
    ]
