# Generated by Django 5.2 on 2025-12-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_auditrecord_collectionlog_contractorrawdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
