# Generated by Django 5.2 on 2025-12-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_alter_contractor_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditrecord',
            name='audit_type',
        ),
        migrations.RemoveField(
            model_name='auditrecord',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='auditrecord',
            name='deepseek_tokens_used',
        ),
        migrations.RemoveField(
            model_name='auditrecord',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='auditrecord',
            name='result_summary',
        ),
        migrations.RemoveField(
            model_name='auditrecord',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='auditrecord',
            name='status',
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='audit_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='collection_rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='gaps_identified',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='positive_signals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='reasoning_trace',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='recommendation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='red_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='sources_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='total_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='auditrecord',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
    ]
