# Generated by Django 5.2 on 2025-12-10 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_remove_auditrecord_audit_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyLienRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50)),
                ('instrument_number', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('MECH_LIEN', "Mechanic's Lien"), ('REL_LIEN', 'Release of Lien'), ('ABS_JUDG', 'Abstract of Judgment'), ('FED_TAX_LIEN', 'Federal Tax Lien'), ('STATE_TAX_LIEN', 'State Tax Lien')], max_length=20)),
                ('grantor', models.CharField(max_length=255)),
                ('grantee', models.CharField(max_length=255)),
                ('filing_date', models.DateField()),
                ('recording_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('match_confidence', models.CharField(blank=True, choices=[('exact', 'Exact Match'), ('fuzzy', 'Fuzzy Match'), ('owner', 'Owner Name Match')], max_length=20, null=True)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('has_release', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_instrument_number', models.CharField(blank=True, max_length=100, null=True)),
                ('days_to_release', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('matched_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lien_records', to='contractors.contractor')),
            ],
            options={
                'db_table': 'county_lien_records',
                'indexes': [models.Index(fields=['grantee'], name='county_lien_grantee_c691a6_idx'), models.Index(fields=['document_type'], name='county_lien_documen_02030a_idx'), models.Index(fields=['filing_date'], name='county_lien_filing__0b9339_idx'), models.Index(fields=['matched_contractor'], name='county_lien_matched_ffef82_idx')],
                'unique_together': {('county', 'instrument_number')},
            },
        ),
    ]
