# Generated by Django 5.2 on 2025-12-22 09:43
# Fix: Add database-level DEFAULT to audit_version column
# The Django model has default=1, but PostgreSQL was missing the DEFAULT constraint
# This caused "null value in column audit_version" errors when any insert issue occurred

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0007_county_lien_records'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE audit_records ALTER COLUMN audit_version SET DEFAULT 1;",
            reverse_sql="ALTER TABLE audit_records ALTER COLUMN audit_version DROP DEFAULT;",
        ),
    ]
