# Generated by Codex on 2026-01-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0008_fix_audit_version_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorVerticalRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=1500)),
                ('rating_adj', models.FloatField(default=1500)),
                ('uncertainty', models.FloatField(default=350)),
                ('comparisons_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('RANKED', 'Ranked'), ('STALE', 'Stale')], default='PROVISIONAL', max_length=20)),
                ('last_compared_at', models.DateTimeField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_ratings', to='contractors.contractor')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_ratings', to='contractors.vertical')),
            ],
            options={
                'unique_together': {('contractor', 'vertical')},
            },
        ),
        migrations.CreateModel(
            name='PairwiseComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.IntegerField(default=50)),
                ('s_winner', models.FloatField(blank=True, null=True)),
                ('expected_a', models.FloatField(blank=True, null=True)),
                ('expected_b', models.FloatField(blank=True, null=True)),
                ('delta_a', models.FloatField(blank=True, null=True)),
                ('delta_b', models.FloatField(blank=True, null=True)),
                ('model_version', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_a', to='contractors.contractor')),
                ('contractor_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_b', to='contractors.contractor')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_comparisons', to='contractors.vertical')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairwise_wins', to='contractors.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('rating_adj', models.FloatField()),
                ('uncertainty', models.FloatField()),
                ('comparisons_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor_vertical_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='contractors.contractorverticalrating')),
                ('source_comparison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_history', to='contractors.pairwisecomparison')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('SEVERE', 'Severe'), ('MODERATE', 'Moderate'), ('MINOR', 'Minor')], default='MODERATE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_events', to='contractors.contractor')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_events', to='contractors.vertical')),
            ],
        ),
    ]

