# Generated by Codex on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0009_leaderboard_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditrecord',
            name='guarantee_analysis',
            field=models.JSONField(default=dict, blank=True),
        ),
    ]
